apiVersion: apps/v1
kind: Deployment
metadata:
    name: covid-server-deploy
    labels:
        app: covid-k8s
spec:
    replicas: 1
    selector:
        matchLabels:
            app: covid-server-app
    template:
        metadata:
            labels:
                app: covid-server-app
        spec:
            containers:
            - name: covid-server-container
              image: covid_server
              imagePullPolicy: Never
              ports:
              - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: covid-server-svc
  labels:
    app: covid-k8s
spec:
  type: NodePort
  ports:
  - port: 50051
    nodePort: 30001
    protocol: TCP
  selector:
    app: covid-server-app

