# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sedgwick_covid.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sedgwick_covid.proto',
  package='sedgwick',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14sedgwick_covid.proto\x12\x08sedgwick\"\x1c\n\x0c\x43ovidRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"7\n\nCovidReply\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x1b\n\x13num_cases_confirmed\x18\x02 \x01(\x05\"\x0f\n\rGetAllRequest2\xa5\x02\n\x0c\x43ovidService\x12\x46\n\x14GetNumCasesConfirmed\x12\x16.sedgwick.CovidRequest\x1a\x14.sedgwick.CovidReply\"\x00\x12;\n\x06GetAll\x12\x17.sedgwick.GetAllRequest\x1a\x14.sedgwick.CovidReply\"\x00\x30\x01\x12<\n\x08GetTotal\x12\x16.sedgwick.CovidRequest\x1a\x14.sedgwick.CovidReply\"\x00(\x01\x12R\n\x1cGetNumCasesConfirmedForDates\x12\x16.sedgwick.CovidRequest\x1a\x14.sedgwick.CovidReply\"\x00(\x01\x30\x01\x62\x06proto3'
)




_COVIDREQUEST = _descriptor.Descriptor(
  name='CovidRequest',
  full_name='sedgwick.CovidRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='sedgwick.CovidRequest.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=62,
)


_COVIDREPLY = _descriptor.Descriptor(
  name='CovidReply',
  full_name='sedgwick.CovidReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='sedgwick.CovidReply.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_cases_confirmed', full_name='sedgwick.CovidReply.num_cases_confirmed', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=119,
)


_GETALLREQUEST = _descriptor.Descriptor(
  name='GetAllRequest',
  full_name='sedgwick.GetAllRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['CovidRequest'] = _COVIDREQUEST
DESCRIPTOR.message_types_by_name['CovidReply'] = _COVIDREPLY
DESCRIPTOR.message_types_by_name['GetAllRequest'] = _GETALLREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CovidRequest = _reflection.GeneratedProtocolMessageType('CovidRequest', (_message.Message,), {
  'DESCRIPTOR' : _COVIDREQUEST,
  '__module__' : 'sedgwick_covid_pb2'
  # @@protoc_insertion_point(class_scope:sedgwick.CovidRequest)
  })
_sym_db.RegisterMessage(CovidRequest)

CovidReply = _reflection.GeneratedProtocolMessageType('CovidReply', (_message.Message,), {
  'DESCRIPTOR' : _COVIDREPLY,
  '__module__' : 'sedgwick_covid_pb2'
  # @@protoc_insertion_point(class_scope:sedgwick.CovidReply)
  })
_sym_db.RegisterMessage(CovidReply)

GetAllRequest = _reflection.GeneratedProtocolMessageType('GetAllRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETALLREQUEST,
  '__module__' : 'sedgwick_covid_pb2'
  # @@protoc_insertion_point(class_scope:sedgwick.GetAllRequest)
  })
_sym_db.RegisterMessage(GetAllRequest)



_COVIDSERVICE = _descriptor.ServiceDescriptor(
  name='CovidService',
  full_name='sedgwick.CovidService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=139,
  serialized_end=432,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetNumCasesConfirmed',
    full_name='sedgwick.CovidService.GetNumCasesConfirmed',
    index=0,
    containing_service=None,
    input_type=_COVIDREQUEST,
    output_type=_COVIDREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAll',
    full_name='sedgwick.CovidService.GetAll',
    index=1,
    containing_service=None,
    input_type=_GETALLREQUEST,
    output_type=_COVIDREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTotal',
    full_name='sedgwick.CovidService.GetTotal',
    index=2,
    containing_service=None,
    input_type=_COVIDREQUEST,
    output_type=_COVIDREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetNumCasesConfirmedForDates',
    full_name='sedgwick.CovidService.GetNumCasesConfirmedForDates',
    index=3,
    containing_service=None,
    input_type=_COVIDREQUEST,
    output_type=_COVIDREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COVIDSERVICE)

DESCRIPTOR.services_by_name['CovidService'] = _COVIDSERVICE

# @@protoc_insertion_point(module_scope)
